[package]
name = "curtain"
version = "0.2.0"
authors = ["jcesar <jovansonlee.cesar@truste.com>"]


[[bin]]
name = "iron_curtain"

#[dependencies.rustorm]
#git = "https://github.com/ivanceras/rustorm.git"

[dependencies.rustorm]
path = "../rustorm"

#[dependencies.codegenta]
#git = "https://github.com/ivanceras/codegenta.git"

[dependencies.codegenta]
path = "../codegenta"


[dependencies]
rustc-serialize = "*"
uuid = "*"
iron = "*"
mount = "*"
router = "*"
persistent = "*"
queryst = "*"
rand = "*"
log = "*"
env_logger = "*"
unicase = "*"
#rustorm = "*"
#codegenta = "*"

[dependencies.chrono]
version = "*"
features = ["rustc-serialize"]


[dependencies.staticfile]
git = "https://github.com/iron/staticfile.git"