[package]
name = "curtain"
version = "0.2.0"
authors = ["jcesar <jovansonlee.cesar@truste.com>"]


[[bin]]
name = "iron_curtain"




[dependencies]
rustc-serialize = "0.3.16"
uuid = "0.1.18"
iron = "0.2.6"
mount = "0.0.9"
router = "0.0.15"
persistent = "0.0.8"
rand = "0.3.12"
log = "0.3.4"
env_logger = "0.3.2"
unicase = "1.1.0"

[dependencies.chrono]
version = "0.2.17"
features = ["rustc-serialize"]

[dependencies.inquerest]
version = "0.0.8"
#path = "../inquerest"

[dependencies.rustorm]
version = "0.4.2"
#path = "../rustorm"

[dependencies.codegenta]
version = "0.0.7"
#path = "../codegenta"




