[package]
name = "curtain"
version = "0.1.0"
authors = ["jcesar <jovansonlee.cesar@truste.com>"]


[[bin]]
name = "iron_curtain"

# [dependencies.rustorm]
# path = "../rustorm"


[dependencies]
rustc-serialize = "*"
uuid = "*"
iron = "*"
mount = "*"
router = "*"
rustorm = "*"

[dependencies.chrono]
version = "*"
features = ["rustc-serialize"]


[dependencies.staticfile]
git = "https://github.com/iron/staticfile.git"