[package]
name = "curtain"
version = "0.1.0"
authors = ["jcesar <jovansonlee.cesar@truste.com>"]


[dependencies.rustorm]
path = "../rustorm"


[dependencies]
rustc-serialize = "*"
uuid = "*"

[dependencies.chrono]
version = "*"
features = ["rustc-serialize"]